[package]

name = "gif"
license = "MIT/Apache-2.0"
version = "0.10.2"
description = "GIF de- and encoder"
authors = ["nwin <nwin@users.noreply.github.com>"]
readme = "README.md"
homepage = "https://github.com/image-rs/image-gif"
repository = "https://github.com/image-rs/image-gif"
documentation = "https://docs.rs/gif"

exclude = [
    "tests/*",
    "gif-afl/*",
]

[dependencies]
lzw = "0.10"
color_quant = "1.0"

[dev-dependencies]
glob = "0.3"

[features]
default = ["raii_no_panic"]
polonius = []

raii_no_panic = []
c_api = ["libc"]

[dependencies.libc]
version = "0.2.1"
optional = true
